language: c

matrix:
  include:
    - os: linux
      dist: xenial
      env: 
        - dist="Xenial 16.x"
        - OCTAVE="flatpak run org.octave.Octave"

install:
  - ./dev-tools/install-octave-flatpak.sh

script:
  # Basic test
  - $OCTAVE --no-gui --eval "ver"
  - $OCTAVE --no-gui --eval 'disp("Hello, world!");'
